name: CVA6-SDK Task
description: Create a CVA6-SDK Project Task
title: "[TASK] <title>"
labels: ["task"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing CVA6-SDK task for this?
    description: Please search to see if a task issue already exists for the task you need to create
    options:
    - label: I have searched the existing task issues
      required: true
- type: textarea
  attributes:
    label: Task Description
    description: A concise description of what needs to be done (user story)
  validations:
    required: true
- type: textarea
  attributes:
    label: Description of Done
    description: What are the criteria for completion of this task?
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Progress
    description: Add notes on current progress
  validations:
    required: false
